@extends('layouts.app')
@section('content')
<section class="dashboard-shell"><div class="container">
    <div class="dashboard-welcome"><div><a class="arrow-link mb-2" href="{{ route('dashboard') }}"><i class="fa-solid fa-arrow-left"></i> Back to dashboard</a><h1>{{ $booking->item_title }}</h1><p class="section-lead">{{ $booking->booking_no }} &middot; Created {{ $booking->created_at->format('d M Y') }}</p></div><span class="status-badge">{{ $booking->workflow_status }}</span></div>
    @php($steps=['Booking Placed','Payment Received','Booking Confirmed','Team Assigned','Team On The Way','Setup Started','Completed'])
    @php($activeIndex=max(0,array_search($booking->tracking_status,$steps,true) ?: 0))
    <div class="dashboard-panel mb-4"><div class="dashboard-panel-head"><h2>Booking progress</h2><a href="{{ route('booking.track',['booking_no'=>$booking->booking_no,'mobile'=>$booking->customer_phone]) }}" class="arrow-link">Public tracker <i class="fa-solid fa-arrow-right"></i></a></div><div class="tracking-timeline compact">@foreach($steps as $index=>$step)<div class="{{ $index <= $activeIndex ? 'complete' : '' }}"><span>@if($index < $activeIndex)<i class="fa-solid fa-check"></i>@else{{ $index+1 }}@endif</span><strong>{{ $step }}</strong></div>@endforeach</div></div>
    <div class="row g-4"><div class="col-lg-8"><div class="dashboard-panel"><div class="dashboard-panel-head"><h2>Event details</h2><i class="fa-regular fa-calendar-check"></i></div><div class="detail-grid"><div><span>Date</span><strong>{{ $booking->event_date->format('d M Y') }}</strong></div><div><span>Time</span><strong>{{ \Illuminate\Support\Str::of($booking->event_time)->substr(0,5) }}</strong></div><div><span>City</span><strong>{{ $booking->city?->name ?? $booking->cityPaymentSetting?->city }}</strong></div><div><span>Area</span><strong>{{ $booking->area?->name ?? $booking->area_name ?? '-' }}</strong></div><div><span>Venue</span><strong>{{ $booking->venue_type ?: '-' }}</strong></div><div><span>Kids / age</span><strong>{{ $booking->number_of_kids }} &middot; {{ $booking->age_group ?: '-' }}</strong></div><div><span>Event type</span><strong>{{ $booking->event_type ?: '-' }}</strong></div><div><span>Address</span><strong>{{ $booking->full_address ?: $booking->location }}</strong></div></div>
        <h2 class="mt-4">Booked items</h2><div class="booking-items-list">@forelse($booking->items as $item)<div><span><strong>{{ $item->item_name }}</strong><small>{{ ucfirst($item->item_type) }} &middot; Qty {{ $item->quantity }}</small></span><b>&#8377;{{ number_format((float)$item->line_total) }}</b></div>@empty<div><span><strong>{{ $booking->item_title }}</strong></span><b>&#8377;{{ number_format((float)$booking->base_amount) }}</b></div>@endforelse</div>
        @if($booking->bookingAddons->isNotEmpty())<h2 class="mt-4">Selected add-ons</h2><div class="booking-addon-list">@foreach($booking->bookingAddons as $addon)<div><img src="{{ $addon->addon?->image_url ?? \App\Models\Addon::fallbackImageUrl() }}" alt="{{ $addon->name }}"><span><strong>{{ $addon->name }}</strong><small>Qty {{ $addon->quantity }}</small></span><b>+&#8377;{{ number_format((float)$addon->price) }}</b></div>@endforeach</div>@endif
        @if($booking->message)<h2 class="mt-4">Special instructions</h2><p class="text-muted">{{ $booking->message }}</p>@endif
        <div class="dashboard-booking-actions"><a class="btn btn-outline-party" href="{{ route('dashboard.booking.rebook',$booking) }}"><i class="fa-solid fa-rotate-right"></i> Rebook</a><a class="btn btn-outline-secondary" href="{{ route('dashboard.booking.invoice',$booking) }}"><i class="fa-solid fa-file-invoice"></i> Invoice</a>@if(!in_array($booking->workflow_status,['Completed','Cancelled','Refunded','Refund Requested']))<button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#cancelModal">Request cancellation</button>@endif</div>
    </div></div><div class="col-lg-4"><div class="dashboard-panel"><div class="dashboard-panel-head"><h2>Payment summary</h2><i class="fa-solid fa-receipt"></i></div><div class="payment-breakdown p-0"><div><span>Service subtotal</span><strong>&#8377;{{ number_format((float)$booking->base_amount) }}</strong></div>@if($booking->coupon_discount>0)<div><span>Coupon discount</span><strong>-&#8377;{{ number_format((float)$booking->coupon_discount) }}</strong></div>@endif<div><span>City fee</span><strong>&#8377;{{ number_format((float)$booking->service_fee) }}</strong></div><div><span>Tax</span><strong>&#8377;{{ number_format((float)$booking->tax_amount) }}</strong></div><div><strong>Total</strong><strong>&#8377;{{ number_format((float)$booking->total_amount) }}</strong></div></div><div class="payment-status-box"><span>Payment status</span><strong>{{ $booking->payment_status }}</strong></div>@if(in_array($booking->payment_status,['Pending','Failed']) && $booking->payable_amount>0)<a href="{{ route('payments.checkout',$booking) }}" class="btn btn-party w-100 mt-3"><i class="fa-solid fa-lock"></i> Pay &#8377;{{ number_format((float)$booking->payable_amount) }}</a>@endif<a class="btn btn-light border w-100 mt-2" href="{{ route('dashboard.booking.invoice',[$booking,'download'=>1]) }}"><i class="fa-solid fa-download"></i> Download invoice</a></div></div></div>
</div></section>
@if(!in_array($booking->workflow_status,['Completed','Cancelled','Refunded','Refund Requested']))<div class="modal fade" id="cancelModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post" action="{{ route('dashboard.booking.cancel',$booking) }}">@csrf<div class="modal-header"><h2 class="modal-title fs-5">Request cancellation</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Reason</label><textarea class="form-control" name="reason" rows="4" required></textarea><p class="small text-muted mt-2 mb-0">Paid bookings create a refund request for admin review.</p></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Keep booking</button><button class="btn btn-danger">Submit request</button></div></form></div></div></div>@endif
@endsection
