@extends('layouts.app')

@section('content')
<section class="page-hero"><div class="container"><span class="eyebrow">Party cart</span><h1>Build the celebration your way.</h1><p>Combine activities, decorations and packages before checkout.</p></div></section>
<section class="section section-soft"><div class="container">
    @if($cart && $cart->items->isNotEmpty())
        <div class="row g-4 align-items-start"><div class="col-lg-8"><div class="cart-list">@foreach($cart->items as $item)<article class="cart-item"><img src="{{ $item->service?->image_url ?? $item->package?->image_url }}" alt="{{ $item->title }}"><div class="cart-item-copy"><span class="mini-label">{{ $item->service_id ? 'Service' : 'Package' }}</span><h2>{{ $item->title }}</h2><p>{{ $cart->city?->name ?? $selectedCity?->name }} pricing</p>@if($item->selected_addons)<div class="cart-addon-list">@foreach($item->selected_addons as $addon)<span><img src="{{ $addon['image'] ?? \App\Models\Addon::fallbackImageUrl() }}" alt="{{ $addon['name'] }}"><b>{{ $addon['name'] }}</b><small>+&#8377;{{ number_format((float) $addon['price']) }}</small></span>@endforeach</div>@endif</div><div class="cart-item-actions"><strong>&#8377;{{ number_format($item->line_total) }}</strong><form method="post" action="{{ route('cart.update', $item->id) }}">@csrf @method('PATCH')<div class="qty-control"><button type="button" data-qty-minus aria-label="Decrease quantity">-</button><input name="quantity" type="number" min="1" max="10" value="{{ $item->quantity }}"><button type="button" data-qty-plus aria-label="Increase quantity">+</button></div><button class="btn btn-outline-secondary btn-sm" type="submit">Update</button></form><form method="post" action="{{ route('cart.destroy', $item->id) }}">@csrf @method('DELETE')<button class="icon-link text-danger" aria-label="Remove {{ $item->title }}"><i class="fa-solid fa-trash"></i></button></form></div></article>@endforeach</div></div><div class="col-lg-4"><aside class="cart-summary"><span class="mini-label">Order summary</span><h2>{{ $cart->items->sum('quantity') }} party item{{ $cart->items->sum('quantity') === 1 ? '' : 's' }}</h2><div><span>Items subtotal</span><strong>&#8377;{{ number_format($cart->subtotal) }}</strong></div><div><span>City</span><strong>{{ $cart->city?->name ?? $selectedCity?->name }}</strong></div><p>City fees, tax and coupon discount are calculated at checkout.</p><a class="btn btn-party btn-lg w-100" href="{{ route('checkout.index') }}">Continue to checkout <i class="fa-solid fa-arrow-right"></i></a><a class="arrow-link justify-content-center mt-3" href="{{ route('services.index') }}">Add more services</a></aside></div></div>
    @else
        <div class="empty-cart"><i class="fa-solid fa-basket-shopping"></i><h2>Your party cart is empty</h2><p>Browse activities, decoration themes and packages to begin.</p><a class="btn btn-party" href="{{ route('services.index') }}">Explore services</a></div>
    @endif
</div></section>
@endsection
