<?php $__env->startSection('content'); ?>
<section class="dashboard-shell"><div class="container">
    <div class="dashboard-welcome"><div><a class="arrow-link mb-2" href="<?php echo e(route('dashboard')); ?>"><i class="fa-solid fa-arrow-left"></i> Back to dashboard</a><h1><?php echo e($booking->item_title); ?></h1><p class="section-lead"><?php echo e($booking->booking_no); ?> &middot; Created <?php echo e($booking->created_at->format('d M Y')); ?></p></div><span class="status-badge"><?php echo e($booking->workflow_status); ?></span></div>
    <?php ($steps=['Booking Placed','Payment Received','Booking Confirmed','Team Assigned','Team On The Way','Setup Started','Completed']); ?>
    <?php ($activeIndex=max(0,array_search($booking->tracking_status,$steps,true) ?: 0)); ?>
    <div class="dashboard-panel mb-4"><div class="dashboard-panel-head"><h2>Booking progress</h2><a href="<?php echo e(route('booking.track',['booking_no'=>$booking->booking_no,'mobile'=>$booking->customer_phone])); ?>" class="arrow-link">Public tracker <i class="fa-solid fa-arrow-right"></i></a></div><div class="tracking-timeline compact"><?php $__currentLoopData = $steps; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $index=>$step): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="<?php echo e($index <= $activeIndex ? 'complete' : ''); ?>"><span><?php if($index < $activeIndex): ?><i class="fa-solid fa-check"></i><?php else: ?><?php echo e($index+1); ?><?php endif; ?></span><strong><?php echo e($step); ?></strong></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div>
    <div class="row g-4"><div class="col-lg-8"><div class="dashboard-panel"><div class="dashboard-panel-head"><h2>Event details</h2><i class="fa-regular fa-calendar-check"></i></div><div class="detail-grid"><div><span>Date</span><strong><?php echo e($booking->event_date->format('d M Y')); ?></strong></div><div><span>Time</span><strong><?php echo e(\Illuminate\Support\Str::of($booking->event_time)->substr(0,5)); ?></strong></div><div><span>City</span><strong><?php echo e($booking->city?->name ?? $booking->cityPaymentSetting?->city); ?></strong></div><div><span>Area</span><strong><?php echo e($booking->area?->name ?? $booking->area_name ?? '-'); ?></strong></div><div><span>Venue</span><strong><?php echo e($booking->venue_type ?: '-'); ?></strong></div><div><span>Kids / age</span><strong><?php echo e($booking->number_of_kids); ?> &middot; <?php echo e($booking->age_group ?: '-'); ?></strong></div><div><span>Event type</span><strong><?php echo e($booking->event_type ?: '-'); ?></strong></div><div><span>Address</span><strong><?php echo e($booking->full_address ?: $booking->location); ?></strong></div></div>
        <h2 class="mt-4">Booked items</h2><div class="booking-items-list"><?php $__empty_1 = true; $__currentLoopData = $booking->items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div><span><strong><?php echo e($item->item_name); ?></strong><small><?php echo e(ucfirst($item->item_type)); ?> &middot; Qty <?php echo e($item->quantity); ?></small></span><b>&#8377;<?php echo e(number_format((float)$item->line_total)); ?></b></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><div><span><strong><?php echo e($booking->item_title); ?></strong></span><b>&#8377;<?php echo e(number_format((float)$booking->base_amount)); ?></b></div><?php endif; ?></div>
        <?php if($booking->bookingAddons->isNotEmpty()): ?><h2 class="mt-4">Selected add-ons</h2><div class="booking-addon-list"><?php $__currentLoopData = $booking->bookingAddons; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $addon): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div><img src="<?php echo e($addon->addon?->image_url ?? \App\Models\Addon::fallbackImageUrl()); ?>" alt="<?php echo e($addon->name); ?>"><span><strong><?php echo e($addon->name); ?></strong><small>Qty <?php echo e($addon->quantity); ?></small></span><b>+&#8377;<?php echo e(number_format((float)$addon->price)); ?></b></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?>
        <?php if($booking->message): ?><h2 class="mt-4">Special instructions</h2><p class="text-muted"><?php echo e($booking->message); ?></p><?php endif; ?>
        <div class="dashboard-booking-actions"><a class="btn btn-outline-party" href="<?php echo e(route('dashboard.booking.rebook',$booking)); ?>"><i class="fa-solid fa-rotate-right"></i> Rebook</a><a class="btn btn-outline-secondary" href="<?php echo e(route('dashboard.booking.invoice',$booking)); ?>"><i class="fa-solid fa-file-invoice"></i> Invoice</a><?php if(!in_array($booking->workflow_status,['Completed','Cancelled','Refunded','Refund Requested'])): ?><button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#cancelModal">Request cancellation</button><?php endif; ?></div>
    </div></div><div class="col-lg-4"><div class="dashboard-panel"><div class="dashboard-panel-head"><h2>Payment summary</h2><i class="fa-solid fa-receipt"></i></div><div class="payment-breakdown p-0"><div><span>Service subtotal</span><strong>&#8377;<?php echo e(number_format((float)$booking->base_amount)); ?></strong></div><?php if($booking->coupon_discount>0): ?><div><span>Coupon discount</span><strong>-&#8377;<?php echo e(number_format((float)$booking->coupon_discount)); ?></strong></div><?php endif; ?><div><span>City fee</span><strong>&#8377;<?php echo e(number_format((float)$booking->service_fee)); ?></strong></div><div><span>Tax</span><strong>&#8377;<?php echo e(number_format((float)$booking->tax_amount)); ?></strong></div><div><strong>Total</strong><strong>&#8377;<?php echo e(number_format((float)$booking->total_amount)); ?></strong></div></div><div class="payment-status-box"><span>Payment status</span><strong><?php echo e($booking->payment_status); ?></strong></div><?php if(in_array($booking->payment_status,['Pending','Failed']) && $booking->payable_amount>0): ?><a href="<?php echo e(route('payments.checkout',$booking)); ?>" class="btn btn-party w-100 mt-3"><i class="fa-solid fa-lock"></i> Pay &#8377;<?php echo e(number_format((float)$booking->payable_amount)); ?></a><?php endif; ?><a class="btn btn-light border w-100 mt-2" href="<?php echo e(route('dashboard.booking.invoice',[$booking,'download'=>1])); ?>"><i class="fa-solid fa-download"></i> Download invoice</a></div></div></div>
</div></section>
<?php if(!in_array($booking->workflow_status,['Completed','Cancelled','Refunded','Refund Requested'])): ?><div class="modal fade" id="cancelModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post" action="<?php echo e(route('dashboard.booking.cancel',$booking)); ?>"><?php echo csrf_field(); ?><div class="modal-header"><h2 class="modal-title fs-5">Request cancellation</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Reason</label><textarea class="form-control" name="reason" rows="4" required></textarea><p class="small text-muted mt-2 mb-0">Paid bookings create a refund request for admin review.</p></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Keep booking</button><button class="btn btn-danger">Submit request</button></div></form></div></div></div><?php endif; ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\kids-party-planner\resources\views\dashboard\booking.blade.php ENDPATH**/ ?>